<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css(array(
    $this->assetTheme('css/front.css'),
    $this->assetTheme('css/animate.min.css'),
));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'href'  => $this->favicon(),
));

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    array('prefix' => array(
        array(
            'label' => __('Home'),
            'href' => Pi::url($this->url('home'))
        )
    ))
);
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?>">
<header class="pi-header">
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="row">
                <div class="navbar-header">
                    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </button>
                    <?php if ($module == 'system') { ?>
                        <h1 class="navbar-brand">
                            <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                <?php echo _escape($sitename); ?>
                            </a>
                        </h1>
                    <?php } else { ?>
                        <h2 class="navbar-brand">
                            <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                <?php echo _escape($sitename); ?>
                            </a>
                        </h2>
                    <?php } ?>
                </div>
                <div class="navbar-collapse collapse">
                    <?php echo $navigation->menu()->setUlClass('nav navbar-nav pi-navbar-nav'); ?>
                    <?php echo $this->widget('system-user-bar'); ?>
                </div>
            </div>
        </div>
    </nav>
    <div class="pi-header-body-text">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="pi-header-information">در صورتی که برگزارکننده تورهای طبیعت گردی و ماجراجویی هستید، اطلاعات تور خود را به رایگان ثبت کنید</div>
                </div>
                <div class="col-md-4">
                    <div class="pi-header-btn">
                        <a itemprop="url" class="btn btn-primary" href="<?php echo Pi::url($this->url('home')); ?>/event/manage" title="ثبت و مدیریت سفر">
                            <span itemprop="name">ثبت و مدیریت سفر</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-header-body">
        <?php if ($module == 'system') { ?>
            <div class="clearfix pi-header-image">
                <div class="pi-header-image-box">
                    <div class="col-md-offset-2 col-md-8">
                        <div class="pi-header-image-text">
                            <p>جستجو بین تور ها و سفر ها</p>
                        </div>
                        <form class="form-inline" method="get" action="#">
                            <div class="form-group">
                                <label>عنوان</label>
                                <input name="title" type="text" class="form-control header-search-title" placeholder="عنوان تور">
                            </div>
                            <div class="form-group">
                                <label>تاریخ تور</label>
                                <select class="form-control header-search-time" name="time">
                                    <option value="">همه</option>
                                    <option value="thisWeek">این هفته</option>
                                    <option value="nextWeek">هفته آینده</option>
                                    <option value="thisMonth">این ماه</option>
                                    <option value="nextMonth">ماه آینده</option>
                                    <option value="nextTwoMonth">دو ماه آینده</option>
                                    <option value="nextThreeMonth">سه ماه آینده</option>
                                     <option value="expired">باطل شده</option>
                                    <option value="active">فعال</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label>شاخه</label>
                                <select class="form-control header-search-category" name="category">
                                    <option value="">همه</option>
                                    <option value="category-3-news">تاریخی</option>
                                    <option value="category-7-news">رصد</option>
                                    <option value="category-5-news">صحرانوردی</option>
                                    <option value="category-2-news">طبیعت گردی</option>
                                    <option value="category-6-news">عکاسی</option>
                                    <option value="category-8-news">ماجراجویی</option>
                                    <option value="category-4-news">کوهنوردی</option>
                                </select>
                            </div>
                            <a class="btn btn-default header-search">یافتن تور</a>
                        </form>
                    </div>
                </div>
                <div class="pi-header-image-image">
                    <picture>
                        <!--[if IE 9]><video style="display: none;"><![endif]-->
                        <source data-srcset="<?php echo $this->assetTheme('image/header-mobi-ete.jpg'); ?>" media="(max-width: 320px)" srcset="<?php echo $this->assetTheme('image/header-mobi-ete.jpg'); ?>">
                        <source data-srcset="<?php echo $this->assetTheme('image/header-smart-ete.jpg'); ?>" media="(max-width: 480px)" srcset="<?php echo $this->assetTheme('image/header-smart-ete.jpg'); ?>">
                        <source data-srcset="<?php echo $this->assetTheme('image/header-tab-ete.jpg'); ?>" media="(max-width: 768px)" srcset="<?php echo $this->assetTheme('image/header-tab-ete.jpg'); ?>">
                        <source data-srcset="<?php echo $this->assetTheme('image/header-lap-ete.jpg'); ?>" media="(max-width: 1366px)" srcset="<?php echo $this->assetTheme('image/header-lap-ete.jpg'); ?>">
                        <source data-srcset="<?php echo $this->assetTheme('image/header-xlap-ete.jpg'); ?>" media="(max-width: 1920px)" srcset="<?php echo $this->assetTheme('image/header-xlap-ete.jpg'); ?>">
                        <source data-srcset="<?php echo $this->assetTheme('image/header-desk-ete.jpg'); ?>" media="(max-width: 2880px)" srcset="<?php echo $this->assetTheme('image/header-desk-ete.jpg'); ?>">
                        <!--[if IE 9]></video><![endif]-->
                        <img class="home-banner img-responsive lazyloaded" data-src="<?php echo $this->assetTheme('image/header-xlap-ete.jpg'); ?>" alt="<?php echo _escape($sitename); ?>" src="<?php echo $this->assetTheme('image/header-xlap-ete.jpg'); ?>">
                    </picture>
                </div>
            </div>
            <div class="pi-header-body-text">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="pi-header-information">
                                <strong>آگاما</strong>فرصت پیدا کردن سغری را که دوست دارید برای شما فراهم می‌کند. این‌جا می‌توانید به دنبال سفری جذاب با هزینه مناسب باشید.
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="pi-header-social">
                                <ul class="list-inline">
                                    <li><a href="#" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a></li>
                                    <li><a href="#" title="Twitter" target="_blank"><i class="fa fa-twitter"></i></a></li>
                                    <li><a href="#" title="Instagram" target="_blank"><i class="fa fa-instagram"></i></a></li>
                                    <li><a href="#" title="Pinterest" target="_blank"><i class="fa fa-pinterest"></i></a></li>
                                    <li><a rel="publisher" href="#" title="Google+" target="_blank"><i class="fa fa-google-plus"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="pi-header-body-category clearfix">
                <div class="thumbnail">
                    <a href="<?php echo Pi::url($this->url('home')); ?>/event/ecotourism" title="طبیعت گردی">
                        <img class="img-responsive" src="<?php echo $this->assetTheme('image/ecotourism.jpg'); ?>" alt="طبیعت گردی">
                    </a>
                    <div class="caption">
                        <h3>
                            <a href="<?php echo Pi::url($this->url('home')); ?>/event/ecotourism" title="طبیعت گردی">طبیعت گردی</a>
                        </h3>
                    </div>
                </div>
                <div class="thumbnail">
                    <a href="<?php echo Pi::url($this->url('home')); ?>/event/adventure" title="ماجراجویی">
                        <img class="img-responsive" src="<?php echo $this->assetTheme('image/adventure.jpg'); ?>" alt="ماجراجویی">
                    </a>
                    <div class="caption">
                        <h3>
                            <a href="<?php echo Pi::url($this->url('home')); ?>/event/adventure" title="ماجراجویی">ماجراجویی</a>
                        </h3>
                    </div>
                </div>
                <div class="thumbnail">
                    <a href="<?php echo Pi::url($this->url('home')); ?>/event/mountaineering" title="کوهنوردی">
                        <img class="img-responsive" src="<?php echo $this->assetTheme('image/mountaineering.jpg'); ?>" alt="کوهنوردی">
                    </a>
                    <div class="caption">
                        <h3>
                            <a href="<?php echo Pi::url($this->url('home')); ?>/event/mountaineering" title="کوهنوردی">کوهنوردی</a>
                        </h3>
                    </div>
                </div>
                <div class="thumbnail">
                    <a href="<?php echo Pi::url($this->url('home')); ?>/event/cross-country" title="صحرانوردی">
                        <img class="img-responsive" src="<?php echo $this->assetTheme('image/cross-country.jpg'); ?>" alt="صحرانوردی">
                    </a>
                    <div class="caption">
                        <h3>
                            <a href="<?php echo Pi::url($this->url('home')); ?>/event/cross-country" title="کویرنوردی">کویرنوردی</a>
                        </h3>
                    </div>
                </div>
                <div class="thumbnail">
                    <a href="<?php echo Pi::url($this->url('home')); ?>/event/observation" title="رصد">
                        <img class="img-responsive" src="<?php echo $this->assetTheme('image/observation.jpg'); ?>" alt="رصد">
                    </a>
                    <div class="caption">
                        <h3>
                            <a href="<?php echo Pi::url($this->url('home')); ?>/event/observation" title="رصد">رصد</a>
                        </h3>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</header>
<section class="pi-section">
    <div class="container">
        <div class="pi-main-container">
            <?php if ($breadcrumbs) { echo $breadcrumbs; } ?>
            <!-- Flash messenger -->
            <?php include $this->template('flash-messenger'); ?>
            <div class="row">
                <!-- Top head zone -->
                <?php if (!empty($blocks['0'])) { ?>
                    <div class="pi-zone-0 col-md-12">
                        <?php foreach ($blocks['0'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <!-- Left zone -->
                <?php if (!empty($blocks['1'])) { ?>
                    <div class="pi-zone-1 col-md-4">
                        <?php foreach ($blocks['1'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <div class="<?php
                if (isset($blocks['1']) && isset($blocks['8'])) {
                    echo 'col-md-4';
                } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                    echo 'col-md-8';
                } else {
                    echo 'col-md-12';
                }
                ?>">
                    <!-- Center top zone -->
                    <?php if (isset($blocks['2'])) { ?>
                        <div class="pi-zone-2">
                            <?php foreach ($blocks['2'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                        <div class="row">
                            <div class="col-md-6 pi-zone-3">
                                <?php
                                if (isset($blocks['3'])) {
                                    foreach ($blocks['3'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-md-6 pi-zone-4">
                                <?php
                                if (isset($blocks['4'])) {
                                    foreach ($blocks['4'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                    <!-- Module content starts -->
                    <?php if (!empty($content)) { ?>
                        <div class="<?php echo $module; ?>">
                            <div class="pi-module-content" ng-app="<?php echo $module; ?>">
                                <?php echo $content; ?>
                            </div>
                            <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                        </div>
                    <?php } ?>
                    <!-- Module content ends -->
                    <?php if (isset($blocks['5']) || isset($blocks['6']) || isset($blocks['7'])) { ?>
                        <div class="row">
                            <div class="col-md-4 pi-zone-5">
                                <?php
                                if (isset($blocks['5'])) {
                                    foreach ($blocks['5'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-md-4 pi-zone-6">
                                <?php
                                if (isset($blocks['6'])) {
                                    foreach ($blocks['6'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                            <div class="col-md-4 pi-zone-7">
                                <?php
                                if (isset($blocks['7'])) {
                                    foreach ($blocks['7'] as $block) {
                                        include $blockTemplate;
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    <?php } ?>
                </div>
                <!-- Right zone -->
                <?php if (isset($blocks['8'])) { ?>
                    <div class="col-md-4 pi-zone-8">
                        <?php foreach ($blocks['8'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>
            <!-- Bottom foot zone -->
            <?php if (isset($blocks['99'])) { ?>
                <div class="pi-zone-99">
                    <?php foreach ($blocks['99'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
            <?php } ?>
        </div>
    </div>
</section>
<footer class="pi-footer">
    <div class="pi-footer-body clearfix">
        <div class="container">
            <div class="row">
                <div class="clearfix">
                    <div class="col-md-7 col-sm-6 col-xs-12">
                        <h2>درباره ما</h2>
                        <p>وب سایت <?php echo _escape($sitename); ?> در بهار ۱۳۹۶ و با هدف مرجعیت آنلاین برای معرفی و ثبت نام در انواع رویداد ها و تور های طبیعت گردی، تاریخی، کوهنوردی، رصد و عکاسی تاسیس شد.</p>
                    </div>
                    <div class="col-md-5 col-sm-6 col-xs-12">
                        <div class="pi-footer-social text-right">
                            <h2>شبکه های اجتماعی</h2>
                            <ul class="list-inline">
                                <li><a target="_blank" title="" href="#"><i class="fa fa-facebook-square"></i></a></li>
                                <li><a target="_blank" title="" href="#"><i class="fa fa-twitter-square"></i></a></li>
                                <li><a target="_blank" title="" href="#"><i class="fa fa-instagram"></i></a></li>
                                <li><a rel="publisher" target="_blank" title="" href="#"><i class="fa fa-google-plus-square"></i></a></li>
                                <li><a target="_blank" title="" href="#"><i class="fa fa-linkedin-square"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="clearfix">
                    <div class="col-md-3 col-sm-3 col-xs-12">
                        <h3>مدت اجرای سفرها</h3>
                        <ul class="list-unstyled">
                            <li><a title="تورهای یک روزه" href="<?php echo Pi::url($this->url('home')); ?>/event"><i class="fa fa-angle-left"></i> تورهای یک روزه</a></li>
                            <li><a title="تورهای چند روزه" href="<?php echo Pi::url($this->url('home')); ?>/event"><i class="fa fa-angle-left"></i> تورهای چند روزه</a></li>
                            <li><a title="تورهای همه روزه" href="<?php echo Pi::url($this->url('home')); ?>/event"><i class="fa fa-angle-left"></i> تورهای همه روزه</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                        <h3>طبقه‌بندی سفرها</h3>
                        <ul class="list-unstyled">
                            <li><a title="طبیعت گردی" href="<?php echo Pi::url($this->url('home')); ?>/event/ecotourism"><i class="fa fa-angle-left"></i> طبیعت گردی</a></li>
                            <li><a title="ماجراجویی" href="<?php echo Pi::url($this->url('home')); ?>/event/adventure"><i class="fa fa-angle-left"></i> ماجراجویی</a></li>
                            <li><a title="کوهنوردی" href="<?php echo Pi::url($this->url('home')); ?>/event/mountaineering"><i class="fa fa-angle-left"></i> کوهنوردی</a></li>
                            <li><a title="کویرنوردی" href="<?php echo Pi::url($this->url('home')); ?>/event/cross-country"><i class="fa fa-angle-left"></i> کویرنوردی</a></li>
                            <li><a title="رصد" href="<?php echo Pi::url($this->url('home')); ?>/event/observation"><i class="fa fa-angle-left"></i> رصد</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                        <h3>نحوه اجرای سفرها</h3>
                        <ul class="list-unstyled">
                            <li><a title="انفرادی" href="<?php echo Pi::url($this->url('home')); ?>/event"><i class="fa fa-angle-left"></i> انفرادی</a></li>
                            <li><a title="دوستانه" href="<?php echo Pi::url($this->url('home')); ?>/event"><i class="fa fa-angle-left"></i> دوستانه</a></li>
                            <li><a title="خانوادگی" href="<?php echo Pi::url($this->url('home')); ?>/event"><i class="fa fa-angle-left"></i> خانوادگی</a></li>
                            <li><a title="کودکان" href="<?php echo Pi::url($this->url('home')); ?>/event"><i class="fa fa-angle-left"></i> کودکان</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-12">
                        <h3>سایر بخش ها</h3>
                        <ul class="list-unstyled">
                            <li><a title="تورها و بلیط ها" href="https://www.agama.ir/event"><i class="fa fa-angle-left"></i> تورها و سفر ها</a></li>
                            <li><a title="درباره ما" href="https://www.agama.ir/page/about-us"><i class="fa fa-angle-left"></i> درباره ما</a></li>
                            <li><a title="تماس با ما" href="https://www.agama.ir/contact"><i class="fa fa-angle-left"></i> تماس با ما</a></li>
                            <li><a title="قوانین و مقررات" href="https://www.agama.ir/page/terms-and-conditions"><i class="fa fa-angle-left"></i> قوانین و مقررات</a></li>
                            <li><a title="راهنمای خرید تور" href="#"><i class="fa fa-angle-left"></i> راهنمای خرید تور</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-copyright clearfix">
        <div class="container">
            <div class="row">
                <div class="text-left col-md-6" data-rel="license">تمام حقوق مطالب برای وب سایت <a href="<?php echo Pi::url($this->url('home')); ?>/" title="<?php echo _escape($sitename); ?>"><?php echo _escape($sitename); ?></a> محفوظ است.
                </div>
                <div class="text-right col-md-6" data-rel="license">طراحی و توسعه <a title="فراگسترش" href="http://www.faragostaresh.com" target="_blank">فراگسترش</a>
                </div>
            </div>
        </div>
    </div>
</footer>
</body>
</html>